apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-front
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: {{ template "name" . }}-front

---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-back
spec:
  ports:
  - port: 6379
  selector:
    app: {{ template "name" . }}-back    