replicas:
  frontend: 1
  backend: 1
imageBackend:
  repository: mcr.microsoft.com/oss/bitnami/redis
  tag: 6.0.8
  pullPolicy: IfNotPresent
imageFrontend: 
  repository: mcr.microsoft.com/azuredocs/azure-vote-front
  tag: v1
  pullPolicy: IfNotPresent
ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  path: /
  host: helm-vote1.20.67.66.98.nip.io